postgresql:
  enabled: true
  primary:
    persistence: 
      enabled: false

configOverrides:
  secret: |
    SECRET_KEY = 'j3iyk1bldRa86wkaf0R15rgoCnuaWFFw2Y1AdGCYGOhs4vkckjZXWVbM'

image:
  repository: 651017398184.dkr.ecr.us-east-2.amazonaws.com/superset-ug
  tag: ~
  pullPolicy: Always

initImage:
  repository: 651017398184.dkr.ecr.us-east-2.amazonaws.com/superset-ug
  tag: latest
  pullPolicy: Always

# supersetNode:
#   connections:
#     db_host: userguiding-sandbox.c1somsjlvjib.us-east-2.rds.amazonaws.com
#     db_port: 5432
#     db_user: postgres
#     db_pass: N2qKh3FLLNYc66rY
#     db_name: superset