version: 0.2
env:
  parameter-store:
    CLUSTER_NAME: "CLUSTER_NAME"
    HELM_PATH: "HELM_PATH"
    ECR_REGISTRY: "ECR_REGISTRY"
    ECR_IMAGE_NAME: "ECR_IMAGE_NAME"
    NAMESPACE: "NAMESPACE"
    ENVIRON: "ENVIRON"
    ROLE_ARN: "ROLE_ARN"
  variables:
    TAG_PREFIX: "build_version_"
phases:
  install:
    commands:
      - ls -al
      - wget -q https://get.helm.sh/helm-v3.6.2-linux-amd64.tar.gz -O helm.tar.gz
      - tar -xzf helm.tar.gz
      - chmod +x ./linux-amd64/helm
      - mv ./linux-amd64/helm /usr/local/bin/helm
    finally:
      - ls -la
  pre_build:
    commands:
      - echo $AWS_REGION
      - echo $CLUSTER_NAME
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      - TAG_VERSION="${TAG_PREFIX}${CODEBUILD_BUILD_NUMBER}"
      - echo $TAG_VERSION
  build:
    commands:
      - docker build --pull --tag $ECR_REGISTRY/$ECR_IMAGE_NAME:$TAG_VERSION ./app/.
    finally:
      - docker push $ECR_REGISTRY/$ECR_IMAGE_NAME:$TAG_VERSION
      - docker tag $ECR_REGISTRY/$ECR_IMAGE_NAME:$TAG_VERSION $ECR_REGISTRY/$ECR_IMAGE_NAME:latest
      - docker push $ECR_REGISTRY/$ECR_IMAGE_NAME:latest
      - helm repo add superset https://apache.github.io/superset
      - helm repo update
      - aws eks --region $AWS_REGION update-kubeconfig --name $CLUSTER_NAME --role-arn $ROLE_ARN
      - kubectl get ns $NAMESPACE || kubectl create ns $NAMESPACE
      - helm upgrade -i $NAMESPACE superset/superset -f ./$ENVIRON/values.yaml --set image.tag=$TAG_VERSION -n $NAMESPACE
